SHELL=/bin/sh
BENCHMARK=is
BENCHMARKU=IS

include ../config/make.def
include ../sys/make.common

${PROGRAM}: config ${OBJS}
	@echo "IS Makefile Currently doing nothing"

clean:
	- rm -f npbparams.jl 
