SHELL=/bin/sh
BENCHMARK=ep
BENCHMARKU=EP

# KCH: nothing here for now
OBJS:=

include ../config/make.def
include ../sys/make.common

${PROGRAM}: config ${OBJS}
	@echo "EP Makefile Currently doing nothing"


clean:
	- rm -f npbparams.jl 



